config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  get '/history', to: 'home#history'
  get '/log',     to: 'home#log'

  resources :matches

end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :opponent, class_name: "User",foreign_key: "opponent_id"
  belongs_to :owner, class_name: "User",foreign_key: "owner_id"

  validates_presence_of :your_score,:their_score,:played_date,:opponent_id
  
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :trackable, :validatable

  has_many :own_registered_matches, class_name:"Match",foreign_key:"owner_id"
  has_many :others_registered_matches, class_name:"Match",foreign_key:"opponent_id"


  def score

  	own_registered_won 		= self.own_registered_matches.select { |match| match.your_score > match.their_score }.count
  	others_registered_won 	= self.others_registered_matches.select { |match| match.your_score < match.their_score }.count

  	return (own_registered_won+others_registered_won)*50

  end

  def total_played_matches
  	return self.own_registered_matches.count + self.others_registered_matches.count
  end

  def all_my_matches
  	 self.own_registered_matches + self.others_registered_matches
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def history
  end

  def log
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
	
	def new
	end

	def create
		#render plain: params[:match].inspect

		@match = Match.new(match_params)
 		@match.owner = current_user
  		@match.save
  		flash[:success] = "Match registered!"

  		redirect_to '/history'


	end

	private
  	def match_params
    	params.require(:match).permit(:your_score, :their_score,:played_date,:opponent_id)
  	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/home/history.html.erb
<h1 class='page-header'>History</h1>

<!-- <div class="alert alert-warning" role="alert">This is a sample page. Replace link in the header with your own.</div> -->


<table class="table table-striped">
  <thead>
    <tr>
      <th>Date</th>
      <th>Opponent</th>
      <th>Score</th>
      <th>Result</th>
      <th colspan="3"></th>
    </tr>
  </thead>
 
  <tbody>
    <% current_user.all_my_matches.sort_by{|m| m.played_date}.each do |match| %>
      <tr>
        <td><%= match.played_date %></td>
        <td><%= match.opponent ? match.opponent.email : "---"  %><small> <%= match.opponent == current_user ? "( *registered by other )" : "" %></small>  </td>
        <td><%= match.your_score.to_s  + "-" +  match.their_score.to_s %></td>
        <td><%= (match.your_score > match.their_score) ? "W" : ( match.your_score < match.their_score ?  "L": "Tie")  %></td>

      </tr>
    <% end %>
  </tbody>
</table>


<%#= image_tag('history.png') %>

app/views/home/index.html.erb
<h1 class='page-header'>Leaderboard</h1>

<!-- <div class="alert alert-warning" role="alert">This is a sample page.</div> -->


<table class="table table-striped" >
  <thead>
    <tr>
      <th>Rank</th>
      <th>Email</th>
      <th>Score</th>
      <th>Games Played</th>
      <th colspan="3"></th>
    </tr>
  </thead>
 
  <tbody>
    <% User.all.sort_by{|u| -u.score}.each_with_index do |user,index| %>
      <tr>

        <td><%= index+1 %></td>
        <td><%= user.email %></td>
        <td><%= user.score %></td>
        <td><%= user.total_played_matches %></td>

      </tr>
    <% end %>
  </tbody>
</table>



<%#= image_tag('leaderboard.png') %>

app/views/home/log.html.erb
<h1 class='page-header'>Log Game</h1>

<!-- <div class="alert alert-warning" role="alert">This is a sample page. Replace link in the header with your own.</div> -->



<%= form_for  :match, url: matches_path  do |form| %>

	<p>
		<%= form.label :played_date %><br>
		<%= form.date_field :played_date, data:{ provide:'datepicker' },:required => true %>
	</p>

	<p>
		<%= form.label :opponent_user %><br>
		<%#= form.collection_select :opponent, User.all.order(:email),:id,:email, 
	                                                       include_blank: true %>
	    <%= form.select :opponent_id, User.all.select{|u| u != current_user }.collect {|c| [c.email, c.id]},:required => true %>
	</p>  

	<p>
		<%= form.label :your_score %><br>
		<%= form.number_field :your_score,:required => true %>
	</p>

	<p>
		<%= form.label :their_score %><br>
		<%= form.number_field :their_score,:required => true%>
	</p>

	<p>
		<%= form.submit %>
	</p>

<% end %>

<%#= image_tag('log_game.png') %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Pingpong</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= link_to 'Log Game', '/log', class: 'btn btn-success navbar-btn' %>
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to 'Leadboard', root_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><a href="/history">History</a></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pingpong Leaderboard</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css", integrity: "sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==", crossorigin: "anonymous" %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js", integrity: "sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==", crossorigin: "anonymous" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>

  

  <%= render 'layouts/header' %>

  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>

  <div class='container'>
    <%= yield %>
  </div>
</body>
</html>